### PR TITLE
better errors, bug fixed

### LINKED ISSUE #10: Untis name should not be unqiue
When register a new user the untis name should not be unique because somebody could then just steal the untis name and its not that relevant.

### LINKED ISSUE #11: Better error handling in the user controller
In the user controller you don't check if the database query was successful or returned an error. If the database query returns a error response with a internal error or smth like that

### LINKED ISSUE #12: Change property name BASEURL in backend .env file
Currently the BASEURL is used for the frontend url in the email verfication. So you should rename it to FRONTEND_URL or smth like that. The frontend url also should be added to the cors rule

### PR DESCRIPTION
**Pull request by elekius**
checked if user was created in user controller
changed the env for BASEURL to FRONTEND_URL
wrote better error messages
made variable naming more consistent

Resolves #10 , resolves #11, resolves #12

### CODE REVIEW

File: backend/internal/controller/user_controller.go [hunk 1]
```diff
@@ -50,27 +53,27 @@ func LoginUser(c *gin.Context) {
...
-		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
+		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid body json. Contact the frontend dev"})
 		c.Abort()
 		return
 	}
 
 	user, err := repo.GetUser(request.Email)
 	if err != nil {
-		c.JSON(http.StatusBadRequest, gin.H{"error": err})
+		c.JSON(http.StatusBadRequest, gin.H{"error": "User with provided email does not exists"})
```
Comment (ChikyuKido) [inline backend/internal/controller/user_controller.go:63]: maybe return here Invalid credentials too.

File: backend/internal/controller/verification_controller.go [hunk 2]
```diff
@@ -17,28 +17,27 @@ import (
...
-		c.JSON(401, gin.H{"error": "unauthorized"})
+		c.JSON(401, gin.H{"error": "Unauthorized"})
 		c.Abort()
 		return
 	}
 
     user, ok := userInterface.(models.User)
     if !ok {
-        c.JSON(401, gin.H{"error": "invalid user type"})
+        c.JSON(401, gin.H{"error": "Invalid user type"})
```
Comment (ChikyuKido) [inline backend/internal/controller/verification_controller.go:27]: internal error

File: backend/internal/controller/verification_controller.go [hunk 3]
```diff
@@ -17,28 +17,27 @@ import (
...
         c.Abort()
         return
     }
 
 	user, err := repo.GetUser(user.Email)
```
Comment (ChikyuKido) [inline backend/internal/controller/verification_controller.go:32]: you already have the user or?

File: backend/internal/controller/verification_controller.go [hunk 4]
```diff
@@ -86,14 +85,14 @@ func VerifyEmail(c *gin.Context) {
 
 	verificationRecord := database.New().Instance().Where("uuid = ?", uuid).First(&verification)
```
Comment (ChikyuKido) [inline backend/internal/controller/verification_controller.go:86]: move this to a repo

File: backend/internal/controller/verification_controller.go [hunk 5]
```diff
@@ -86,14 +85,14 @@ func VerifyEmail(c *gin.Context) {
...
 	if verificationRecord.Error != nil {
-		c.JSON(http.StatusBadRequest, gin.H{"error": verificationRecord.Error})
+		c.JSON(http.StatusBadRequest, gin.H{"error": "failed to get users verification info"})
 		c.Abort()
 		return
 	}
 
     userRecord := database.New().Instance().Where("id = ?", verification.UserID).First(&user)
```
Comment (ChikyuKido) [inline backend/internal/controller/verification_controller.go:93]: move this to a repo

**Review by ChikyuKido — COMMENTED** [review]
move some database queries to a query and if a query really fails its always an internal error

File: backend/internal/controller/verification_controller.go [hunk 6]
```diff
@@ -24,7 +24,7 @@ func SendVerificationEmail(c *gin.Context) {
 
     user, ok := userInterface.(models.User)
     if !ok {
-        c.JSON(401, gin.H{"error": "Invalid user type"})
+        c.JSON(401, gin.H{"error": "Internal Error"})
```
Comment (ChikyuKido) [inline backend/internal/controller/verification_controller.go:27]: 401 is unauthorized use 500 for internal server error

**Review by ChikyuKido — COMMENTED** [review]
Change response code to  internal server error

**Review by ChikyuKido — APPROVED** [review]
Looks good
